# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches: 
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'oracle'
        server-id: central 
        server-username: ${{ secrets.MAVEN_USERNAME }}
        server-password: ${{ secrets.MAVEN_PASSWORD }}
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
    - name: Import GPG Key
      run: |
        gpg --list-secret-keys --keyid-format LONG
    - name: Build and Deploy packages to Maven
      run: mvn clean deploy -Dhttps.protocols=TLSv1.2
      env:
        GITHUB_TOKEN: ${{ github.token }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
